spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: 'jdbc:mysql://localhost:3306/expresssystem?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8'
    username: root
    password: 2002
    druid:
      filters: stat,wall,slf4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      initial-size: 20
      max-active: 20
      min-idle: 20
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 100
      validation-query: select 'x' from dual
      validation-query-timeout: 10
      stat-view-servlet:
        url-pattern: "/druid/*"
        login-username: zzy
        login-password: 2002
        reset-enable: false
        enabled: true
      driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 19001
